Fixes #6: Indicator matching
tweaselORG/TrackHAR pull request #15
Opened 2023-05-25 17:57 UTC by baltpeter

2023-06-02 12:25 UTC, zner0L requested changes
Other than a stray comment, this seems fine!

2023-06-02 12:25 UTC, zner0L commented on src/index.ts
> + *   respective part of the request.
This is a duplicate.
```suggestion
```

2023-06-02 16:05 UTC, baltpeter commented on src/index.ts
> + *   respective part of the request.
Um, no it isn't?

2023-06-05 15:20 UTC, zner0L approved these changes

2023-06-05 15:20 UTC, merged