Port over more adapters from baltpeter/thesis-mobile-consent-dialogs
tweaselORG/TrackHAR pull request #2
Opened 2023-04-05 16:07 UTC by baltpeter

2023-04-08 15:27 UTC, zner0L requested changes
I am looking forward to get those tested and adding more!

2023-04-08 15:27 UTC, zner0L commented on src/adapters/google.ts
> +        reasoning: 'obvious property name',
I don‘t find that obvious.

2023-04-08 15:27 UTC, zner0L commented on src/adapters/google.ts
> +                reasoning: 'obvious property name',
This is not obvious.

2023-04-09 10:31 UTC, baltpeter commented on src/index.ts
> +    | 'hashedIdfa'
I don't think so. Do you know my password if you know `hash(password)`?

2023-04-09 10:34 UTC, baltpeter commented on src/adapters/infonline.ts
> +                reasoning: 'obvious observed values',
I know my gaid and I know `md5(gaid)`. I observed `md5(gaid)`.

2023-04-09 10:38 UTC, baltpeter commented on src/adapters/chartboost.ts
> +                reasoning: 'obvious property name',
But then you couldn't say that `1280` obviously means screen height, either. And we don't have a way to document further research into these yet.

I'm consider this PR as a port of the existing adapters without much in the way of thought or verification. I definitely plan on going over these again once we have the time and a way to document things.

2023-04-09 10:40 UTC, baltpeter commented on src/adapters/infonline.ts
> +                    path: 'client.uuids.androidId',
Why would `uuids.androidId` be an OS version? :o

2023-04-09 10:41 UTC, baltpeter commented on src/adapters/adcolony.ts
> +        endpointUrls: [/^https:\/\/(android|ios)?ads\d-?\d\.adcolony\.com\/configure$/],
#5

2023-04-09 10:42 UTC, baltpeter commented on src/adapters/branch-io.ts
> +                    path: 'metadata.$marketing_cloud_visitor_id',
![image](https://user-images.githubusercontent.com/4048809/230768077-5420bcba-3fdc-4bcc-9d04-432d4d330a62.png)

2023-04-09 10:50 UTC, baltpeter commented on src/adapters/google.ts
> +        reasoning: 'obvious property name',
It's `net=wi`, so you couldn't call the values obvious, either. To properly document that, I'd need our wiki thingy.

2023-04-09 10:51 UTC, baltpeter commented on src/adapters/google.ts
> +                reasoning: 'obvious property name',
Most of the IDs need proper documentation that I can't provide yet.

A few sample values:

```
device=5726602953696069553
device=5452258145332196440
device=4856623273933326178
```

2023-04-11 11:59 UTC, zner0L commented on src/index.ts
> +    | 'hashedIdfa'
No. But in this case it has the same result, doesn't it? If I have an unique identifier or the (unique) of an unique identifier doesn't really matter in the end for the purpose of identifying me, does it? I guess it makes cross tracking a little more difficult.

2023-04-11 12:00 UTC, zner0L commented on src/adapters/chartboost.ts
> +                reasoning: 'obvious property name',
Shouldn't we at least put a TODO placeholder here then?

2023-04-11 12:04 UTC, zner0L commented on src/adapters/infonline.ts
> +                reasoning: 'obvious observed values',
I know that you saw that in your experiments. But I would like to treat "obvious observed values" as though anyone can easily guess the data type from the data type just by looking at it, so something like "Android" for example, which is obviously the OS.

2023-04-11 12:05 UTC, zner0L commented on src/adapters/infonline.ts
> +                    path: 'client.uuids.androidId',
Ah, `uuid` stand for unique user ID, doesn't it?

2023-04-11 12:05 UTC, baltpeter commented on src/index.ts
> +    | 'hashedIdfa'
But we are explicitly distinguishing between the IDFA (which pretty much all authorities and even companies recognize as personal data) and other identifiers (which Facebook for examples likes to call "anonymous", as you saw). Lumping in things that are not unambiguously the IDFA would weaken that (even though you and I of course agree that there is no functional difference).

If anything, you could put this into `otherIdentifiers` instead. But I do think the additional category is warranted due to the special nature of the IDFA.

2023-04-11 12:12 UTC, baltpeter commented on src/adapters/infonline.ts
> +                reasoning: 'obvious observed values',
That would be nice, sure. But we don't have any other way to express this yet.

And it would mean that you could never use this reasoning for the gaid or IDFA. Both are just standard UUIDs that could also be something else entirely.

2023-04-11 12:13 UTC, zner0L approved these changes

2023-04-11 12:14 UTC, merged