Towards tweaselORG/meta#36: Add auto-archiving script
tweaselORG/TrackHAR pull request #54
Opened 2023-09-23 14:21 UTC by zner0L

2023-09-25 07:52 UTC, baltpeter requested changes

2023-09-25 07:52 UTC, baltpeter commented on scripts/lib/wayback.ts
> +    /** Capture a web page with errors (HTTP status=4xx or 5xx). By default SPN2 captures only status=200 URLs. */
The comments are offset by one.

2023-09-25 07:52 UTC, baltpeter commented on scripts/lib/wayback.ts
> +    /** An optional message from the API, e.g. telling you you capture will be delayed for some reason. */
```suggestion
    /** An optional message from the API, e.g. telling you your capture will be delayed for some reason. */
```

2023-09-25 07:52 UTC, baltpeter commented on scripts/lib/wayback.ts
> +          /** Status emitted if the capture was successful. */
Same here.

2023-09-25 07:52 UTC, baltpeter commented on scripts/lib/wayback.ts
> +    /** The capture encountered an error. */
And here.

2023-09-25 07:52 UTC, baltpeter commented on archive-config.example.json
> +        "s3AccessKey": "Obtain me at https://archive.org/account/s3.php.",
The trailing period is unfortunate with a link.

2023-09-25 07:52 UTC, baltpeter commented on research-docs/archived-urls.csv
> +"https://github.com/mopub/mopub-ios-sdk/blob/4b5e70e4ff69b0c3f4ab71a8791f5e7351ad2828/MoPubSDK/Internal/MPAdServerKeys.m","https://web.archive.org/web/20220222115549/https://github.com/mopub/mopub-io
I would also scope captures at least to the adapter, maybe even to the property. What if we have archived a page a while ago and then are doing work on a new adapter but the page has changed in the meantime? Without this scoping, we would have no way to have captures of both states of the URL (and the auto archiver would just ignore the new page).

Also, I would include a timestamp. For Wayback Machine captures, I guess that's already included in the URL but that's hard to access, and archive.today URLs don't have a timestamp in the URL.

2023-09-25 07:52 UTC, baltpeter commented on scripts/archive-links.ts
> +    const urlCSV = parse(urlFile, { bom: true, delimiter: ',' });
`urlCsv`

2023-09-25 07:52 UTC, baltpeter commented on scripts/archive-links.ts
> +    await Promise.all(
Unless I've missed something and the code in the previous commit is already doing concurrency limiting, this should definitely use https://github.com/sindresorhus/p-map or https://github.com/sindresorhus/p-queue to avoid hitting the API with too many requests at once.

2023-09-25 07:52 UTC, baltpeter commented on package.json
> +        "auto-archive": "tsx watch scripts/archive-links.ts",
Heh. But won't that abort mid-archive if I save while a capture is still in progress?

2023-09-25 11:13 UTC, zner0L commented on research-docs/archived-urls.csv
> +"https://github.com/mopub/mopub-ios-sdk/blob/4b5e70e4ff69b0c3f4ab71a8791f5e7351ad2828/MoPubSDK/Internal/MPAdServerKeys.m","https://web.archive.org/web/20220222115549/https://github.com/mopub/mopub-io
This is only realistic for adding new properties, though. I think detecting a property has been changed (and therefore updating the archived URL) might be a bit much.

2023-09-25 11:15 UTC, baltpeter commented on research-docs/archived-urls.csv
> +"https://github.com/mopub/mopub-ios-sdk/blob/4b5e70e4ff69b0c3f4ab71a8791f5e7351ad2828/MoPubSDK/Internal/MPAdServerKeys.m","https://web.archive.org/web/20220222115549/https://github.com/mopub/mopub-io
Yes.

2023-09-29 08:15 UTC, baltpeter requested changes
This is working better than I expected it to. :D Nice!

2023-09-29 08:15 UTC, baltpeter commented on research-docs/README.md
> +If you want to URLs you add to the adapter `reasoning` to be archived automatically, you can run `yarn auto-archive` and keep it running, while you edit the files. You’ll need to create an `archive-c
Maybe add a note that all the `ExperimentalWarnings` are normal? I thought the script was constantly crashing and restarting at first.

2023-09-29 08:15 UTC, baltpeter commented on scripts/archive-links.ts
> +        { concurrency: 5 }
Well, at least in my testing now, I didn't get any errors archiving five items at the same time. *shrug*

2023-09-29 08:15 UTC, baltpeter commented on scripts/lib/wayback.ts
> +    const captureResult = await capture(url, auth, options);
The `captureResult` can already have an error, in which case we should abort here:

```
archiving http://localhost:3000
archiving https://web.archive.org/web/20230000000000*/https://www.bfdi.bund.de/SharedDocs/Stellenangebote/DE/0439_Stellenangebot_IT_Experten_Abt_2.html

cr {
  message: 'http://localhost:3000 URL syntax is not valid.',
  status: 'error',
  status_ext: 'error:invalid-url-syntax'
}
cr {
  message: 'This URL is in the Save Page Now service block list and cannot be captured. Please email us at "info@archive.org" if you would like to discuss this more.',
  status: 'error',
  status_ext: 'error:blocked-url'
}
```

Otherwise, we'll continue doing useless status requests until we time out:

```
sr { job_id: 'undefined', resources: [], status: 'pending' }
sr { job_id: 'undefined', resources: [], status: 'pending' }
sr { job_id: 'undefined', resources: [], status: 'pending' }
sr { job_id: 'undefined', resources: [], status: 'pending' }
[…]
Timed out while waiting for archiving status of "https://web.archive.org/web/20230000000000*/https://www.bfdi.bund.de/SharedDocs/Stellenangebote/DE/0439_Stellenangebot_IT_Experten_Abt_2.html".
 -> Affected data paths: google/app-measurement#appVersion
Timed out while waiting for archiving status of "http://localhost:3000".
 -> Affected data paths: google/app-measurement#appId
```

2023-09-29 08:22 UTC, zner0L commented on research-docs/README.md
> +The properties must be a string in the format `<tracker slug>/<adapter slug>#<property name>`, e.g. `mopub/ads#screenHeight`. They must not be escaped by `"` characters.
I guess "wrapped in" is a better way of putting it?

2023-09-29 08:24 UTC, baltpeter commented on research-docs/README.md
> +The properties must be a string in the format `<tracker slug>/<adapter slug>#<property name>`, e.g. `mopub/ads#screenHeight`. They must not be escaped by `"` characters.
Yes. But I still don't understand what you're saying. They _are_ wrapped in quotes in the CSV?

2023-09-29 08:27 UTC, zner0L commented on research-docs/README.md
> +The properties must be a string in the format `<tracker slug>/<adapter slug>#<property name>`, e.g. `mopub/ads#screenHeight`. They must not be escaped by `"` characters.
Yes, but only the whole array, not each property identifier.

2023-09-29 08:29 UTC, baltpeter commented on research-docs/README.md
> +The properties must be a string in the format `<tracker slug>/<adapter slug>#<property name>`, e.g. `mopub/ads#screenHeight`. They must not be escaped by `"` characters.
I don't think I would have ever considered doing that. If you really think we need to mention that, you should make it more explicit.

2023-09-29 08:30 UTC, zner0L commented on research-docs/README.md
> +If you want to URLs you add to the adapter `reasoning` to be archived automatically, you can run `yarn auto-archive` and keep it running, while you edit the files. You’ll need to create an `archive-c
What warnings? I am not getting any.

2023-09-29 08:32 UTC, baltpeter commented on research-docs/README.md
> +If you want to URLs you add to the adapter `reasoning` to be archived automatically, you can run `yarn auto-archive` and keep it running, while you edit the files. You’ll need to create an `archive-c
For me, this beautiful output is produced in the first ~20 seconds:

```
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1130809) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/benni/coding/JS/tweasel/TrackHAR/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(nod [...]

2023-09-29 08:33 UTC, zner0L commented on research-docs/README.md
> +If you want to URLs you add to the adapter `reasoning` to be archived automatically, you can run `yarn auto-archive` and keep it running, while you edit the files. You’ll need to create an `archive-c
Interesting. What node version are you using?

2023-09-29 08:35 UTC, baltpeter commented on research-docs/README.md
> +If you want to URLs you add to the adapter `reasoning` to be archived automatically, you can run `yarn auto-archive` and keep it running, while you edit the files. You’ll need to create an `archive-c
`nvm install; nvm use` with your `.nvmrc` gave me `v20.8.0`.

2023-09-29 08:37 UTC, zner0L commented on research-docs/README.md
> +If you want to URLs you add to the adapter `reasoning` to be archived automatically, you can run `yarn auto-archive` and keep it running, while you edit the files. You’ll need to create an `archive-c
Interesting. I got no errors in node v20.7.0, they must have just release the new version.

2023-09-29 08:38 UTC, baltpeter commented on research-docs/README.md
> +If you want to URLs you add to the adapter `reasoning` to be archived automatically, you can run `yarn auto-archive` and keep it running, while you edit the files. You’ll need to create an `archive-c
Oh wow, indeed. With v20.7.0, I get no errors, either.

2023-09-29 12:52 UTC, zner0L commented on scripts/archive-links.ts
> +                    timestamp: parseInt(savePageResult.captureStatus.timestamp, 10),
We can’t extract a timezone from this either way, but I agree.

2023-10-05 11:17 UTC, zner0L commented on research-docs/README.md
> +If you want to URLs you add to the adapter `reasoning` to be archived automatically, you can run `yarn auto-archive` and keep it running, while you edit the files. You’ll need to create an `archive-c
This seems to be a general issue with `tsx`: https://github.com/esbuild-kit/tsx/issues/330

2023-10-09 11:41 UTC, baltpeter commented on scripts/archive-links.ts
> +            .catch(() => {})) as { waybackAuth?: ArchiveOrgAuth } | undefined;
```suggestion
            .catch(() => undefined)) as { waybackAuth?: ArchiveOrgAuth } | undefined;
```

2023-10-26 11:36 UTC, zner0L commented on research-docs/README.md
> +If you want to URLs you add to the adapter `reasoning` to be archived automatically, you can run `yarn auto-archive` and keep it running, while you edit the files. You’ll need to create an `archive-c
I pinned the version down to v20.7.0. The tsx team have fixed the warnings (https://github.com/esbuild-kit/tsx/pull/337), but it breaks our worker threads (https://github.com/esbuild-kit/tsx/issues/354), so would suggest keeping the version pinned until this is fixed entirely.

2023-10-26 11:54 UTC, baltpeter approved these changes
Other than the typo, this looks good now. You can merge yourself after fixing.

2023-10-26 11:54 UTC, baltpeter commented on scripts/lib/archiving.ts
> +export const getReasoningUrlsFromAdapter = async (adapters: Adapter[]) =>
```suggestion
export const getReasoningUrlsFromAdapters = async (adapters: Adapter[]) =>
```

2023-10-26 14:57 UTC, merged