Fixes #75: Adapter for Firebase Remote Config
tweaselORG/TrackHAR pull request #76
Opened 2024-05-06 08:52 UTC by baltpeter

This is based on #59, which needs to be merged first.

2024-06-07 15:54 UTC, zner0L requested changes

2024-06-07 15:54 UTC, zner0L commented on src/adapters/google.ts
> +                    reasoning: 'google/appInstanceIdToken.md',
Same question here. I think we should decode the JWT.

2024-06-10 10:54 UTC, zner0L commented
Created #79 to track JWT decoding and will hold merging until this is closed.

2024-09-24 06:28 UTC, baltpeter commented
This is now based on https://github.com/tweaselORG/TrackHAR/pull/87, which needs to be merged first.

2024-09-24 07:11 UTC, baltpeter commented
The problem this still has is that there is [one app](https://data.tweasel.org/data?sql=select+link%28dataset%2C+id%29%2C+initiator%2C+platform%2C+runType%2C+startTime%2C+method%2C+httpVersion%2C+endpointUrl%2C+scheme%2C+host%2C+port%2C+path%2C+content%2C+headers%2C+cookies+%0D%0Afrom+requests%0D%0AWHERE+path+like+%27%25%2Fv1%2Fprojects%2F330194062051%2Fnamespaces%2Ffirebase%3Afetch%25%27%0D%0Alimit+101+collate+nocase%3B) that [sometimes](https://data.tweasel.org/data/requests/do-they-track,98586) (but not always) sends an `appInstanceIdToken` that is not a JWT: `eCKZbsz5Sde-1eY2P48xBZ:APA91bExD9TtElNISzzjwPLvFRAypKO89dpkU4SGHI4dZpu0thydzo7QqrVnE3gXg6qrb8nCay2F45__K2oL-PHTqy-VeN20yUdbDE7Eym5oFyyPqh_mykAyrnV4Y8eXl713Bg2GMK3r`

This touches on a question that I have been toeing around for a while. Currently, we don't guard against exceptions in decode functions:

https://github.com/tweaselORG/TrackHAR/blob/9287bf182bf18badb8ac93f0e300eec0b4f011c1/src/index.ts#L258

But I am really not sure whether that is "correct". For one, this a problem from the perspective of writing the adapters (as in this case) because we don't have any mechanism to work around this from an adapter. But, and more importantly, I also don't think that this is the correct behaviour semantically. I do think that "try to parse this value as x and ignore it otherwise" makes more sense for the decode functions. This more eager way of writing/understanding adapters also matches how we handle things in other places. Notably, we already gracefully handle empty values without the adapter having to concern itself with them:

https://github.com/tweaselORG/TrackHAR/blob/9287bf182bf18badb8ac93f0e300eec0b4f011c1/src/index.ts#L249

2024-09-24 07:26 UTC, baltpeter commented
Implemented. The commit history should now be kept when merging.

2024-10-03 12:16 UTC, zner0L approved these changes

2024-10-03 12:16 UTC, merged

2024-10-10 12:24 UTC, baltpeter commented
The last force push broke the ID grouping changes: [`183a5a0cd9b33ac18a465b6046573e4c06ed959b..71769496afc63164b7398852f7dc746b083abefd`#diff-6e40c2e22b](https://github.com/tweaselORG/TrackHAR/compare/183a5a0cd9b33ac18a465b6046573e4c06ed959b..71769496afc63164b7398852f7dc746b083abefd#diff-6e40c2e22bd2a3e07e99bc31f85d88156813c70d1558a35bf5cd4bab8040658a)L1632

I'm currently working on various Google adapters for web anyway, so I'll fix this through that PR.