Fixes #46: Filters for `DataPath`s
tweaselORG/TrackHAR pull request #83
Opened 2024-09-16 11:47 UTC by baltpeter

2024-09-24 06:13 UTC, baltpeter commented
This is now based on https://github.com/tweaselORG/TrackHAR/pull/87, which needs to be merged first.

2024-10-03 11:53 UTC, zner0L reviewed
I like the filters for each `DataPath`, but I also think that there are some values which always signify an empty result, such as `none`, `unknown`or `null`. I think we should filter for these as a default to be safe, maybe with the option overwrite this using the `onlyIf` option.

2024-10-03 11:53 UTC, zner0L commented on src/index.ts
> +        typeof v === 'bigint' || typeof v === 'string' || typeof v === 'symbol' || typeof v === 'function'
Where is this list coming from? Can `JSON.stringify()` handle all other JS types?

2024-10-04 09:44 UTC, baltpeter commented on src/index.ts
> +        typeof v === 'bigint' || typeof v === 'string' || typeof v === 'symbol' || typeof v === 'function'
Manual testing by me. Yep.

2024-10-04 09:45 UTC, baltpeter commented
> I like the filters for each `DataPath`, but I also think that there are some values which always signify an empty result, such as `none`, `unknown`or `null`. I think we should filter for these as a default to be safe, maybe with the option overwrite this using the `onlyIf` option.

Yeah, that's a good idea. I'll implement it. I don't think implementing overrides would be practical, but I really don't think they should be necessary, either.

2024-10-09 10:10 UTC, zner0L requested changes

2024-10-09 10:10 UTC, zner0L commented on src/index.ts
> +                            "''",
Please update the README accordingly.

2024-10-10 06:50 UTC, baltpeter commented on src/index.ts
> +                            "''",
But the README already mentions the behaviour? https://github.com/tweaselORG/TrackHAR/pull/83/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R255

Or, if you're talking specifically about the quotes, it deliberately wasn't a complete list before this commit, either.

2024-10-16 19:26 UTC, zner0L submitted a review, later dismissed

2024-10-16 19:42 UTC, merged