Adapters for GTM and Google Analytics
tweaselORG/TrackHAR pull request #91
Opened 2024-10-11 13:27 UTC by baltpeter

This is yet again using features from #83, but not based on it. Also, the `check-archived` script fails (rightfully) because we are missing an archive link for `http://code.google.com/apis/analytics/docs/concepts/gaConceptsCookies.html`. I unfortunately can't fetch that right now since some… [not so nice people] are DDOSing the Internet Archive (and the original site isn't up anymore, so I can't use archive.today instead, either). -.-

The Google Analytics adapters is quite massive. It can handle ~75k requests from our database!

2024-10-14 08:54 UTC, baltpeter commented
> Also, the `check-archived` script fails (rightfully) because we are missing an archive link for `http://code.google.com/apis/analytics/docs/concepts/gaConceptsCookies.html`. I unfortunately can't fetch that right now since some… [not so nice people] are DDOSing the Internet Archive (and the original site isn't up anymore, so I can't use archive.today instead, either). -.-

Resolved, now that the Wayback Machine sort of works again.

2024-10-17 15:58 UTC, zner0L requested changes
This must have been a lot of work. But it will pay off. Thank you! I found a few typos, maybe you can have a look.

2024-10-17 15:58 UTC, zner0L commented on i18n/de.json
> +        "isUserInactive": "Ist die Nutzer_in inaktiv?",
How is this different from `isUserActive: false`?

2024-10-17 15:58 UTC, zner0L commented on i18n/de.json
> +        "google-analytics": "Google Analytics ist eine Analyseplattform, die Publishern ein vollständiges Verständnis ihrer Kund_innen über Geräte und Plattformen hinweg verspricht, um zu verstehen,
```suggestion
        "google-analytics": "Google Analytics ist eine Analyseplattform, die Publishern ein vollständiges Verständnis ihrer Kund_innen über Geräte und Plattformen hinweg verspricht, um zu verstehen, wie diese über Webseiten und Apps hinweg während ihres gesamten Lebenszyklus interagieren. („complete understanding of [their] customers across devices and platforms“, „[u]nderstand how [their] customers interact across […] sites and apps, throughout their entire lifecycle.“[https://marketingplatform.google.com/about/analytics/])\n\nGoogle Analytics stellt JavaScript-Bibliotheken, SDKs für mobile Apps und ein offenes Messprotokoll bereit, um Daten von Webseiten-Besucher_innen und App-Nutzer_innen zu sammeln.[https://marketingplatform.google.com/about/analytics/features/] Jedes Mal, wenn eine Nutzer_in eine Webseite besucht, sammelt der Tracking-Code pseudonyme Informationen darüber, wie diese Nutzer_in mit der Seite interagiert hat.[https://support.google.com/analytics/answer/12159447] Darauf aufbauend bietet Google zusätzliche Funktionen:\n\n- Echtzeit-Berichterstattung, die es Publishern ermöglicht, Aktivitäten auf ihrer Webseite oder App in Echtzeit zu überwachen.[https://marketingplatform.google.com/about/analytics/features/]\n- Attribution, die es Publishern ermöglicht, die Wege ihrer Kund_innen zur Conversion zu verstehen.[https://marketingplatform.google.com/about/analytics/features/]\n- Pfad- und Nutzer_innenexploration. Publisher können die Wege ihrer Nutzer_innen zur Conversion visualisieren, während diese mit ihrer Webseite und App interagieren.[https://marketingplatform.google.com/about/analytics/features/] Sie können sogar bestimmte Gruppen von Nutzer_innen auswählen und tiefer bohren, um zu verstehen, wie diese Nutzer_innen mit der Webseite oder App interagieren.[https://marketingplatform.google.com/about/analytics/features/]\n- Funnel-Exploration: Publisher können die Schritte visualisieren, die Nutzer_innen unternehmen, um Aufgaben auf der Webseite oder App abzuschließen sowie über- oder unterdurchschnittlich performende Zielgruppen identifizieren.“[https://marketingplatform.google.com/about/analytics/features/]\n- Prädiktive Fähigkeiten: Durch die Anwendung von maschinellen Lernmodellen will Google Analytics die Daten der Publisher analysieren und zukünftige Aktionen vorhersagen, die Menschen tätigen könnten, wie einen Kauf zu tätigen oder abzuwandern. Die Publisher können dann Zielgruppen erstellen, von denen vorhergesagt wird, dass sie diese Aktionen durchführen werden, um Conversions zu steigern oder mehr ihrer Nutzer_innen zu halten.“[https://marketingplatform.google.com/about/analytics/features/]\n\nGoogle Analytics integriert sich mit verschiedenen anderen Google-Produkten, einschließlich Google Ads, Google Search Ads 360, Google Search Console und Google Play.[https://marketingplatform.google.com/about/analytics/features/]\n\nEs gab mehrere Generationen von Google Analytics. Die aktuelle Generation ist Google Analytics 4 (GA4). Die vorherige Generation, Universal Analytics, hat im Juli 2023 die Datenverarbeitung eingestellt. Sie verwendete Property-Tags, die mit „UA-“ begannen.[https://support.google.com/analytics/answer/11583528]",
```

2024-10-17 15:58 UTC, zner0L commented on i18n/de.json
>          "isFirstLaunch": "Ist dies der erste Start?",
```suggestion
        "isFirstLaunch": "Ist dies der erste Start/Besuch?",
```
Analogous to the English translation

2024-10-17 15:58 UTC, zner0L commented on src/adapters/google.ts
> +                    path: 'tid',
Is `'__GTM_DEFAULT_TRACKER__'` not found in the query?

2024-10-18 06:40 UTC, baltpeter commented on i18n/de.json
> +        "isUserInactive": "Ist die Nutzer_in inaktiv?",
It's not. But some trackers transfer `isUserInactive: false` instead of `isUserActive: true` and adapters have no way of transforming observed values (we can't say `isUserActive := !body.isUserInactive`).

Precedent: `diskFree`, `diskUsed`, `diskTotal`. You can convey all this information using any two of those and easily calculate the missing one from that.

2024-10-18 06:42 UTC, baltpeter commented on i18n/de.json
> +        "google-analytics": "Google Analytics ist eine Analyseplattform, die Publishern ein vollständiges Verständnis ihrer Kund_innen über Geräte und Plattformen hinweg verspricht, um zu verstehen,
@github Can you plz try a little harder with the diff highlighting? :(

2024-10-18 06:44 UTC, baltpeter commented on src/adapters/google.ts
> +                    path: 'tid',
Not in my testing (I didn't actually investigate this but if I had to guess, it's just one website/WordPress plugin/… that is misconfigured).

But I guess if you want, we can filter it out here just in case. *shrug*

2024-11-27 15:26 UTC, zner0L approved these changes

2024-11-27 15:27 UTC, merged